### PR TITLE
IIITBH-IITP

### PR DESCRIPTION
**Pull request by Saichethan**
1. 
[https://github.com/WING-NUS/scisumm-corpus/blob/master/2018-evaluation-script/program/task1_eval.py](https://github.com/WING-NUS/scisumm-corpus/blob/master/2018-evaluation-script/program/task1_eval.py) replace "annv3.csv" to ".csv"

2.  
if anyone is facing WordNet error 
```
/scisumm-corpus/2018-evaluation-script/program/rouge/data$ rm WordNet-2.0.exc.db

/scisumm-corpus/2018-evaluation-script/program/rouge/data$ ./WordNet-2.0-Exceptions/buildExeptionDB.pl ./WordNet-2.0-Exceptions ./smart_common_words.txt ./WordNet-2.0.exc.db
```
3. Still cumulative Task1 B results are not present in scores.txt

### CODE REVIEW

**Comment by dennlinger** [comment]
According to the script `program/run.sh`, results for the overall tasks should be present in `./input/res/Task1/`, however, there is no such folder generated currently. Am I right in assuming that this would contain the final scores used for evaluation?

**Comment by Saichethan** [comment]
@dennlinger results(here I mean scores) will be present in the output directory. Whereas  `./input/res/Task1/` contains our submitted CSV files

**Comment by dennlinger** [comment]
No, `.input/ref/` contains the input files. However, if you look at line 3 in the aforementioned script, it states `input/res/`, which is different (`s`, not `f`). Further, script `task1_eval.py`, which is called indirectly by the same script, then uses *this specific input parameter*, to write the overall evaluation of the task (see ll. 489-501 in script `task1_eval.py`). According to my understanding, the written values consider the results across *all files*, instead of the currently generated output over one file only.

**Comment by Saichethan** [comment]
For a single run, these two results are written in score.txt

t12
and
t11

which of these should I report system description paper?

**Comment by cmkumar87** [comment]
@dennlinger @Saichethan  Thanks for this discussion! I had made he change in rename.py from .txt to .csv. I won't merge this PR to an evaluation script to be fair to all participants.

**Comment by cmkumar87** [comment]
@dennlinger It is very unlikely that we have errors in how scores are computed since the script has not been changed since 2018. So please double check and confirm if you are reporting bug (as a separate github issue). Note that we check the system output files against multiple reference / ground truth files for each reference document (3 annotators).

**Comment by Saichethan** [comment]
@cmkumar87 @dennlinger  My intentions are just to cross-check if I am doing the evaluation correctly...

**Comment by cmkumar87** [comment]
@Saichethan @dennlinger   Is this change required to run the script? 
https://github.com/WING-NUS/scisumm-corpus/blob/master/2018-evaluation-script/program/task1_eval.py replace "annv3.csv" to ".csv"

If so I will make it to the repo; please run the script from the repo and not the modified version from your fork.

I am not merging this PR for fairness to other contestants since this is from a participant. thanks!

**Comment by cmkumar87** [comment]
@Saichethan   Your PR is not going into your evaluation folder but to 2018-evaluation-scripts. I am not able to merge any pull request outside of the your evaluation folder. Also from the PR I am not able to find scores for all the runs in your submission. Please advise and raise a new PR

**Comment by Saichethan** [comment]
@cmkumar87 all my runs scores are in https://github.com/Saichethan/scisumm-corpus/tree/master/2018-evaluation-script/setup. Should I add this to the CLSciSumm_2020_Evaluation folder? are there any naming conventions bcz 43-IIITBH-IITP folder is already present

**Comment by Saichethan** [comment]
please check once now, if the updated version is in alignment with your requirements?

**Pull request merged**
